---
:host: 127.0.0.1
:port: 8989
:io_port: 8988
:title: My mpd queue
:mpd_host: 127.0.0.1
:mpd_port: 6600
:version: false # set to string to display, with false it'll try use git --describe
# options below are not mandatory, you can delete them
:contact: mailto:your@mail.address
:stream_playlist: http://link.to/playlist.m3u # can be an array
:stream_direct: http://direct.stream/url # can be an array
# for the following to work you need at least one stream_direct URL defined,
# in case of an array it will use only the first entry
:stream_widget: false
:stream_format: audio/ogg
:info_title: Help
:info_text: Some text # you need to set info_title above too for this to work
:counter: false # show online users counter
:album_art: false # try to fetch and show album art from iTunes
 # generate a 'buy now' link, by substituting "artist album", so an example
 # shop_link value: http://www.amazon.com/s/field-keywords=%s
 # works only if album_art is enabled and album art has been found
:shop_link: false
